# Predictive comparison: estuary flow

In [ ]:
estuary.shape

(1020, 18)

In [ ]:
print('Train obs: 731 Test obs: 289')

Train obs: 731 Test obs: 289

In [ ]:
print(estuary['salinity_gap'].isna().sum()/estuary.shape[0]*100)
print(estuary['tidal_range'].isna().sum()/estuary.shape[0]*100)

8.4
3.1

In [ ]:
estuary['salinity_gap'].fillna(estuary['salinity_gap'].median(), inplace=True)
pd.get_dummies(estuary['season'])
np.log10(estuary['tidal_range'])

In [ ]:
summary(y_test, cedar_pred, model_name='Cedar')
summary(y_test, willow_pred, model_name='Willow')
summary(y_test, delta_pred, model_name='Delta')

Cedar
[[180 22]
 [ 41 46]]
ROC AUC: 0.812
Accuracy: 0.782
Recall: 0.529
Precision: 0.676
F1 score: 0.593
Willow
[[174 28]
 [ 38 49]]
ROC AUC: 0.743
Accuracy: 0.772
Recall: 0.563
Precision: 0.636
F1 score: 0.597
Delta
[[169 33]
 [ 35 52]]
ROC AUC: 0.701
Accuracy: 0.765
Recall: 0.598
Precision: 0.612
F1 score: 0.605

In [ ]:
feature_importances = fitted_estimator.feature_importances_

                    importance
tidal_range            0.271
salinity_gap           0.219
canopy_density         0.153
river_proximity        0.121
season                  0.094

## Check sensitivity to observation window

In [ ]:
run_window_sensitivity()

ValueError: required window feature was not persisted